#!/usr/bin/env bun

const colors = await Bun.file(import.meta.dir + "/colors.txt").text()

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

// shadcn-style semantic aliases mapped to existing theme tokens
const aliases: Record<string, string> = {
  background: "background-base",
  foreground: "text-base",
  muted: "surface-base",
  "muted-foreground": "text-weak",
  destructive: "surface-critical-base",
  "destructive-foreground": "text-on-critical-base",
  border: "border-base",
  input: "input-base",
  ring: "border-interactive-base",
  primary: "surface-brand-base",
  "primary-foreground": "text-on-brand-base",
  accent: "surface-interactive-base",
  "accent-foreground": "text-on-interactive-base",
  popover: "surface-raised-stronger-non-alpha",
  "popover-foreground": "text-strong",
  card: "surface-raised-stronger",
  "card-foreground": "text-strong",
  secondary: "button-secondary-base",
  "secondary-foreground": "text-base",
  success: "surface-success-base",
  "success-foreground": "text-on-success-base",
  warning: "surface-warning-base",
  "warning-foreground": "text-on-warning-base",
  info: "surface-info-base",
  "info-foreground": "text-on-info-base",
  canvas: "bg-canvas",
  chrome: "bg-chrome",
  sidebar: "bg-sidebar",
  panel: "bg-panel",
  well: "bg-well",
  subtle: "bg-subtle",
  elevated: "bg-elevated",
  overlay: "bg-overlay",
  scrim: "bg-scrim",
}

const aliasLines = Object.entries(aliases).map(([name, token]) => `--color-${name}: var(--${token});`)

const output = `
/* Generated by script/tailwind.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}

  /* shadcn-style semantic aliases */
  ${aliasLines.join("\n  ")}
}
`

await Bun.file(import.meta.dir + "/../src/styles/tailwind/colors.css").write(output.trim())
