import type { AffordanceSource, ProjectionDefinition } from "./types"

const entries: ProjectionDefinition[] = [
  {
    id: "whiteboards",
    label: "Whiteboards",
    description: "Excalidraw diagrams stored as .whiteboard files in the workspace.",
    layout: "canvas",
    query: { kind: "files", extensions: [".whiteboard"] },
    icon: "whiteboards",
    domain: "general",
    create: { label: "New whiteboard" },
  },
  {
    id: "notes",
    label: "Notes",
    description: "Quick capture cards — thoughts without folders or filenames.",
    layout: "cards",
    query: { kind: "store", type: "note" },
    icon: "notes",
    domain: "general",
    create: { label: "New note", entityType: "note" },
  },
  {
    id: "calendar",
    label: "Calendar",
    description: "Issues, work units, and milestones on a monthly calendar.",
    layout: "calendar",
    query: { kind: "trellis", view: "calendar" },
    icon: "calendar",
    domain: "general",
  },
  {
    id: "content",
    label: "Content",
    description: "Page-like CMS collections, arranged for editing copy and structured sections.",
    layout: "table",
    query: { kind: "cms", collections: ["pages", "content", "sections"], match: "exact" },
    icon: "content",
    domain: "web",
    create: { label: "New content", collection: "content" },
    stub: true,
  },
  {
    id: "posts",
    label: "Posts",
    description: "Blog, article, and update collections for publishing workflows.",
    layout: "table",
    query: { kind: "cms", collections: ["posts", "articles", "blog"], match: "exact" },
    icon: "posts",
    domain: "web",
    create: { label: "New post", collection: "posts" },
    stub: true,
  },
  {
    id: "media",
    label: "Media",
    description: "Image, video, and reusable visual assets for the current workspace.",
    layout: "cards",
    query: { kind: "assets", category: ["image", "video"] },
    icon: "media",
    domain: "media",
    stub: true,
  },
  {
    id: "records",
    label: "Records",
    description: "App and productivity records across user-defined CMS collections.",
    layout: "table",
    query: { kind: "cms", collections: ["records", "tasks", "items"], match: "exact" },
    icon: "records",
    domain: "app",
    create: { label: "New record", collection: "records" },
    stub: true,
  },
  {
    id: "catalog",
    label: "Catalog",
    description: "Commerce catalog collections for products, categories, and merchandising.",
    layout: "table",
    query: { kind: "cms", collections: ["products", "collections", "catalog"], match: "exact" },
    icon: "catalog",
    domain: "commerce",
    create: { label: "New catalog item", collection: "products" },
    stub: true,
  },
  {
    id: "products",
    label: "Products",
    description: "Product records with pricing, imagery, and storefront metadata.",
    layout: "table",
    query: { kind: "cms", collections: ["products"], match: "exact" },
    icon: "products",
    domain: "commerce",
    create: { label: "New product", collection: "products" },
    stub: true,
  },
  {
    id: "metrics",
    label: "Metrics",
    description: "KPIs, datasets, and dashboard metric definitions.",
    layout: "table",
    query: { kind: "cms", collections: ["metrics", "kpis", "datasets"], match: "exact" },
    icon: "metrics",
    domain: "data",
    create: { label: "New metric", collection: "metrics" },
    stub: true,
  },
  {
    id: "levels",
    label: "Levels",
    description: "Level, stage, and map records for game projects.",
    layout: "cards",
    query: { kind: "cms", collections: ["levels", "stages", "maps"], match: "exact" },
    icon: "levels",
    domain: "game",
    create: { label: "New level", collection: "levels" },
    stub: true,
  },
  {
    id: "entities",
    label: "Entities",
    description: "Characters, items, NPCs, and gameplay entities.",
    layout: "cards",
    query: { kind: "cms", collections: ["characters", "items", "npcs", "entities"], match: "exact" },
    icon: "entities",
    domain: "game",
    create: { label: "New entity", collection: "entities" },
    stub: true,
  },
  {
    id: "decks",
    label: "Decks",
    description: "Presentation decks and narrative containers.",
    layout: "cards",
    query: { kind: "cms", collections: ["decks", "presentations"], match: "exact" },
    icon: "decks",
    domain: "writing",
    create: { label: "New deck", collection: "decks" },
    stub: true,
  },
  {
    id: "slides",
    label: "Slides",
    description: "Editable slide records, speaker notes, and sequencing.",
    layout: "cards",
    query: { kind: "cms", collections: ["slides"], match: "exact" },
    icon: "slides",
    domain: "writing",
    create: { label: "New slide", collection: "slides" },
    stub: true,
  },
  {
    id: "scenes",
    label: "Scenes",
    description: "Scenes, shots, and production beats for video work.",
    layout: "list",
    query: { kind: "cms", collections: ["scenes", "shots"], match: "exact" },
    icon: "scenes",
    domain: "media",
    create: { label: "New scene", collection: "scenes" },
    stub: true,
  },
  {
    id: "scripts",
    label: "Scripts",
    description: "Scripts, captions, and spoken-word writing surfaces.",
    layout: "list",
    query: { kind: "cms", collections: ["scripts", "captions"], match: "exact" },
    icon: "scripts",
    domain: "writing",
    create: { label: "New script", collection: "scripts" },
    stub: true,
  },
  {
    id: "articles",
    label: "Articles",
    description: "Documentation, articles, and long-form publishing collections.",
    layout: "table",
    query: { kind: "cms", collections: ["docs", "articles", "pages"], match: "exact" },
    icon: "articles",
    domain: "writing",
    create: { label: "New article", collection: "articles" },
    stub: true,
  },
  {
    id: "links",
    label: "Links",
    description: "Saved links and external references connected to project entities.",
    layout: "list",
    query: { kind: "assets", category: ["links"] },
    icon: "links",
    domain: "web",
    stub: true,
  },
  {
    id: "shotlist",
    label: "Shotlist",
    description: "Shot planning, production checklists, and capture status.",
    layout: "list",
    query: { kind: "cms", collections: ["shotlist", "shots"], match: "exact" },
    icon: "shotlist",
    domain: "media",
    create: { label: "New shot", collection: "shotlist" },
    stub: true,
  },
  {
    id: "orders",
    label: "Orders",
    description: "Commerce order records and fulfillment status.",
    layout: "table",
    query: { kind: "cms", collections: ["orders"], match: "exact" },
    icon: "orders",
    domain: "commerce",
    create: { label: "New order", collection: "orders" },
    stub: true,
  },
  {
    id: "themes",
    label: "Themes",
    description: "Visual themes, tokens, and presentation style variants.",
    layout: "cards",
    query: { kind: "cms", collections: ["themes"], match: "exact" },
    icon: "themes",
    domain: "writing",
    create: { label: "New theme", collection: "themes" },
    stub: true,
  },
  {
    id: "audio",
    label: "Audio",
    description: "DAW-style audio assets, cues, stems, and sound design notes.",
    layout: "list",
    query: { kind: "assets", category: ["audio"] },
    icon: "audio",
    domain: "audio",
    stub: true,
  },
  {
    id: "sprites",
    label: "Sprites",
    description: "Sprite sheets, atlas regions, and game art assets.",
    layout: "cards",
    query: { kind: "assets", category: ["sprites", "image"] },
    icon: "sprites",
    domain: "game",
    stub: true,
  },

  // --- Affordances: personal / OS-style apps ---
  {
    id: "bookmarks",
    label: "Bookmarks",
    description: "Saved pages, references, and reading list entries.",
    layout: "table",
    query: { kind: "cms", collections: ["bookmarks", "links"], match: "exact" },
    icon: "bookmarks",
    domain: "general",
    create: { label: "New bookmark", collection: "bookmarks" },
  },
  {
    id: "contacts",
    label: "Contacts",
    description: "People, organizations, and the relationships between them.",
    layout: "table",
    query: { kind: "cms", collections: ["contacts", "people", "organizations"], match: "exact" },
    icon: "contacts",
    domain: "general",
    create: { label: "New contact", collection: "contacts" },
  },
  {
    id: "moodboards",
    label: "Moodboards",
    description: "Visual collections — imagery, references, and inspiration boards.",
    layout: "cards",
    query: { kind: "assets", category: ["image"] },
    icon: "moodboards",
    domain: "media",
  },
  {
    id: "voicememos",
    label: "Voice memos",
    description: "Recorded audio notes, clips, and spoken captures.",
    layout: "list",
    query: { kind: "assets", category: ["audio"] },
    icon: "voicememos",
    domain: "audio",
  },
  {
    id: "places",
    label: "Places",
    description: "Locations, addresses, and points of interest.",
    layout: "list",
    query: { kind: "cms", collections: ["places", "locations"], match: "exact" },
    icon: "places",
    domain: "general",
    create: { label: "New place", collection: "places" },
  },
  {
    id: "clock",
    label: "Clock",
    description: "Alarms, reminders, timers, and a stopwatch.",
    layout: "utility",
    query: { kind: "store", type: "clock" },
    icon: "clock",
    domain: "general",
  },
  {
    id: "journal",
    label: "Journal",
    description: "Daily timestamped markdown entries in the workspace.",
    layout: "list",
    query: { kind: "files", extensions: [".md"] },
    icon: "journal",
    domain: "writing",
    create: { label: "Today" },
  },
  {
    id: "cron",
    label: "Cron",
    description: "Scheduled shell, agent, and journal jobs for the workspace.",
    layout: "utility",
    query: { kind: "store", type: "cron_job" },
    icon: "cron",
    domain: "app",
    create: { label: "New job" },
  },

  // --- Affordances: future shells (placeholder only for now) ---
  {
    id: "music",
    label: "Music",
    description: "Playlists, tracks, and listening — coming soon.",
    layout: "list",
    query: { kind: "store", type: "music" },
    icon: "music",
    domain: "audio",
    stub: true,
    comingSoon: true,
  },
  {
    id: "mail",
    label: "Mail",
    description: "Inbox, threads, and composing — coming soon.",
    layout: "list",
    query: { kind: "store", type: "mail" },
    icon: "mail",
    domain: "app",
    stub: true,
    comingSoon: true,
  },
  {
    id: "messages",
    label: "Messages",
    description: "Direct messages and conversations — coming soon.",
    layout: "list",
    query: { kind: "store", type: "messages" },
    icon: "messages",
    domain: "app",
    stub: true,
    comingSoon: true,
  },
  {
    id: "feeds",
    label: "Feeds",
    description: "Social and content feeds — coming soon.",
    layout: "list",
    query: { kind: "store", type: "feeds" },
    icon: "feeds",
    domain: "web",
    stub: true,
    comingSoon: true,
  },
  {
    id: "books",
    label: "Books",
    description: "Library, reading, and highlights — coming soon.",
    layout: "list",
    query: { kind: "store", type: "books" },
    icon: "books",
    domain: "writing",
    stub: true,
    comingSoon: true,
  },
  {
    id: "camera",
    label: "Camera",
    description: "Photos and captures — coming soon.",
    layout: "cards",
    query: { kind: "store", type: "camera" },
    icon: "camera",
    domain: "media",
    stub: true,
    comingSoon: true,
  },
]

const REGISTRY = new Map<string, ProjectionDefinition>(entries.map((entry) => [entry.id, entry]))

export const BUILTIN_PROJECTION_IDS = new Set(REGISTRY.keys())

function withSource(entry: ProjectionDefinition, source: AffordanceSource): ProjectionDefinition {
  return entry.source === source ? entry : { ...entry, source }
}

function mergedRegistry(custom?: ProjectionDefinition[]): Map<string, ProjectionDefinition> {
  const map = new Map<string, ProjectionDefinition>()
  for (const entry of REGISTRY.values()) {
    map.set(entry.id, withSource(entry, "builtin"))
  }
  if (!custom) return map
  for (const entry of custom) {
    map.set(entry.id, entry)
  }
  return map
}

export function getProjection(id: string, custom?: ProjectionDefinition[]): ProjectionDefinition | undefined {
  const customEntry = custom?.find((entry) => entry.id === id)
  if (customEntry) return customEntry
  const builtin = REGISTRY.get(id)
  return builtin ? withSource(builtin, "builtin") : undefined
}

export function listProjections(ids: string[], custom?: ProjectionDefinition[]): ProjectionDefinition[] {
  const registry = mergedRegistry(custom)
  return ids.flatMap((id) => {
    const entry = registry.get(id)
    return entry ? [entry] : []
  })
}

export function allProjections(custom?: ProjectionDefinition[]): ProjectionDefinition[] {
  return [...mergedRegistry(custom).values()]
}
