import { readFileSync, writeFileSync, mkdirSync } from "fs"
import { join } from "path"

const root = process.cwd()
const appLib = join(root, "packages/app/src/lib/catalog")

type CatalogIcon = {
  key: string
  library: "lucide" | "custom"
  tags: string[]
  category?: string
}

const LUCIDE_CATEGORY_PATTERNS: Record<string, string[]> = {
  Arrows: ["arrow", "chevron", "move", "navigation"],
  Communication: ["mail", "message", "phone", "chat", "send", "share"],
  Media: ["image", "video", "camera", "film", "music", "play", "pause"],
  Files: ["file", "folder", "document", "archive", "download", "upload"],
  UI: ["menu", "settings", "more", "close", "check", "x", "plus", "minus"],
  Shapes: ["circle", "square", "triangle", "hexagon", "pentagon"],
  Data: ["database", "table", "chart", "graph", "bar", "line"],
  Time: ["clock", "calendar", "timer", "alarm"],
  Users: ["user", "users", "person", "people"],
  Business: ["briefcase", "building", "store", "shop"],
  Nature: ["leaf", "tree", "flower", "sun", "moon", "cloud"],
  Food: ["coffee", "utensils", "apple", "cherry"],
  Transport: ["car", "bike", "plane", "train", "ship"],
  Other: [],
}

function categorizeLucide(name: string): string {
  const lower = name.toLowerCase()
  for (const [category, patterns] of Object.entries(LUCIDE_CATEGORY_PATTERNS)) {
    if (category === "Other") continue
    if (patterns.some((pattern) => lower.includes(pattern))) return category
  }
  return "Other"
}

function loadLucide() {
  const candidates = [
    join(root, "node_modules/@iconify-json/lucide/icons.json"),
    join(root, "../www/node_modules/@iconify-json/lucide/icons.json"),
  ]
  for (const path of candidates) {
    try {
      return JSON.parse(readFileSync(path, "utf-8")) as {
        icons: Record<string, { body: string; categories?: string[]; tags?: string[] }>
      }
    } catch {
      // try next path
    }
  }
  throw new Error("Could not load @iconify-json/lucide/icons.json — run bun install in turtlecode/ide")
}

try {
  mkdirSync(appLib, { recursive: true })

  const lucide = loadLucide()
  const glyphs: Record<string, string> = {}
  const lucideIcons: CatalogIcon[] = []
  const byCategory = new Map<string, CatalogIcon[]>()

  for (const [name, data] of Object.entries(lucide.icons)) {
    glyphs[name] = data.body
    const icon: CatalogIcon = {
      key: name,
      library: "lucide",
      tags: data.tags ?? [],
      category: data.categories?.[0] ?? categorizeLucide(name),
    }
    lucideIcons.push(icon)
    const bucket = byCategory.get(icon.category!) ?? []
    bucket.push(icon)
    byCategory.set(icon.category!, bucket)
  }

  lucideIcons.sort((a, b) => a.key.localeCompare(b.key))

  const lucideCategories = Array.from(byCategory.entries())
    .map(([name, icons]) => ({
      name,
      icons: icons.sort((a, b) => a.key.localeCompare(b.key)),
    }))
    .sort((a, b) => {
      if (a.name === "Other") return 1
      if (b.name === "Other") return -1
      return a.name.localeCompare(b.name)
    })

  writeFileSync(
    join(appLib, "lucide-glyphs.ts"),
    `// Generated by script/generate-icon-catalog.ts — do not edit.
export const LUCIDE_GLYPHS: Record<string, string> = ${JSON.stringify(glyphs, null, 2)}
`,
  )

  writeFileSync(
    join(appLib, "lucide-catalog.json"),
    JSON.stringify({ icons: lucideIcons, categories: lucideCategories, totalCount: lucideIcons.length }, null, 2),
  )

  const customRaw = JSON.parse(
    readFileSync(join(root, "packages/app/src/assets/icons/icons.json"), "utf-8"),
  ) as Array<{ name: string; tags?: string[] }>

  const customIcons: CatalogIcon[] = customRaw
    .map((icon) => ({
      key: icon.name,
      library: "custom" as const,
      tags: icon.tags ?? [],
      category: "Custom",
    }))
    .sort((a, b) => a.key.localeCompare(b.key))

  writeFileSync(
    join(appLib, "custom-catalog.json"),
    JSON.stringify({ icons: customIcons, categories: [{ name: "Custom", icons: customIcons }], totalCount: customIcons.length }, null, 2),
  )

  const opencodeLib = join(root, "packages/opencode/src/design/catalog")
  mkdirSync(opencodeLib, { recursive: true })
  writeFileSync(join(opencodeLib, "lucide-catalog.json"), JSON.stringify({ icons: lucideIcons, categories: lucideCategories, totalCount: lucideIcons.length }, null, 2))
  writeFileSync(join(opencodeLib, "custom-catalog.json"), JSON.stringify({ icons: customIcons, categories: [{ name: "Custom", icons: customIcons }], totalCount: customIcons.length }, null, 2))

  console.log(`Generated ${lucideIcons.length} Lucide glyphs and ${customIcons.length} custom catalog entries`)
} catch (error) {
  console.error("Error generating icon catalog:", error)
  process.exit(1)
}
