
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const inputPath = join(process.cwd(), "packages/app/src/assets/icons/icons.json");
const outputPath = join(process.cwd(), "packages/app/src/lib/generated-icons.ts");

try {
  const rawData = readFileSync(inputPath, "utf-8");
  const icons = JSON.parse(rawData);

  const iconMap: Record<string, string> = {};

  for (const icon of icons) {
    // Extract inner content from <svg ...> inner </svg>
    const match = icon.svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
    if (match && match[1]) {
      iconMap[icon.name] = match[1].trim();
    }
  }

  const fileContent = `// This file is generated by script/generate-icons.ts
export const GENERATED_ICONS: Record<string, string> = ${JSON.stringify(iconMap, null, 2)};
`;

  writeFileSync(outputPath, fileContent);
  console.log(`Successfully generated ${Object.keys(iconMap).length} icons to ${outputPath}`);
} catch (error) {
  console.error("Error generating icons:", error);
  process.exit(1);
}
