/** Re-export document helpers (browser-safe; no Node corpus loader). */
export type { WhiteboardDocument } from "@opencode-ai/whiteboard/browser"
export {
  WHITEBOARD_EXT,
  EPHEMERAL_APP_STATE_KEYS,
  EXCALIDRAW_DEFAULT_STORAGE_KEY,
  excalidrawLocalStorageKey,
  excalidrawStorageKeysForPath,
  isWhiteboardPath,
  emptyWhiteboard,
  STUDIO_WHITEBOARD_APP_STATE,
  STUDIO_WHITEBOARD_UI_OPTIONS,
  sanitizeAppStateForStorage,
  prepareExcalidrawScene,
  prepareExcalidrawInitialData,
  repairExcalidrawLocalStorage,
  parseWhiteboard,
  inspectWhiteboardRaw,
  serializeWhiteboard,
  type WhiteboardInspectResult,
  whiteboardTitle,
  defaultWhiteboardPath,
  dedupeWhiteboardPath,
  slugFromWhiteboardPath,
  isSketchWhiteboardPath,
  whiteboardEntityId,
  hasVisibleElements,
  needsVisualPreview,
  sceneElementsKey,
  serializeWhiteboardRenderMeta,
  whiteboardRenderPaths,
} from "@opencode-ai/whiteboard/browser"
